// Verified references (web-searched DOI/arXiv links). Each entry: key, formatted IEEE-style line.
// Numbering shown is the canonical "library" numbering — each paper picks its own subset and renumbers.
module.exports = {
  R: {
    Lewis2020: 'P. Lewis, E. Perez, A. Piktus, F. Petroni, V. Karpukhin, N. Goyal, H. Küttler, M. Lewis, W. Yih, T. Rocktäschel, S. Riedel, and D. Kiela, "Retrieval-Augmented Generation for Knowledge-Intensive NLP Tasks," in Adv. Neural Inf. Process. Syst. (NeurIPS), vol. 33, 2020, pp. 9459–9474. arXiv:2005.11401.',
    Karpukhin2020: 'V. Karpukhin, B. Oğuz, S. Min, P. Lewis, L. Wu, S. Edunov, D. Chen, and W. Yih, "Dense Passage Retrieval for Open-Domain Question Answering," in Proc. EMNLP, 2020, pp. 6769–6781.',
    Izacard2021: 'G. Izacard and E. Grave, "Leveraging Passage Retrieval with Generative Models for Open Domain Question Answering," in Proc. EACL, 2021, pp. 874–880.',
    Guu2020: 'K. Guu, K. Lee, Z. Tung, P. Pasupat, and M. Chang, "REALM: Retrieval-Augmented Language Model Pre-Training," in Proc. ICML, vol. 119, 2020, pp. 3929–3938.',
    Borgeaud2022: 'S. Borgeaud, A. Mensch, J. Hoffmann et al., "Improving Language Models by Retrieving from Trillions of Tokens," in Proc. ICML, vol. 162, 2022, pp. 2206–2240.',
    Robertson2009: 'S. Robertson and H. Zaragoza, "The Probabilistic Relevance Framework: BM25 and Beyond," Foundations and Trends in Information Retrieval, vol. 3, no. 4, pp. 333–389, 2009. doi:10.1561/1500000019.',
    Trotman2014: 'A. Trotman, A. Puurula, and B. Burgess, "Improvements to BM25 and Language Models Examined," in Proc. Australasian Document Computing Symp. (ADCS), 2014, pp. 58–66.',
    Ji2023: 'Z. Ji, N. Lee, R. Frieske, T. Yu, D. Su, Y. Xu, E. Ishii, Y. J. Bang, A. Madotto, and P. Fung, "Survey of Hallucination in Natural Language Generation," ACM Computing Surveys, vol. 55, no. 12, art. 248, 2023.',
    Shuster2021: 'K. Shuster, S. Poff, M. Chen, D. Kiela, and J. Weston, "Retrieval Augmentation Reduces Hallucination in Conversation," in Findings of EMNLP, 2021, pp. 3784–3803.',
    Bohnet2022: 'B. Bohnet, V. Q. Tran, P. Verga et al., "Attributed Question Answering: Evaluation and Modeling for Attributed Large Language Models," arXiv:2212.08037, 2022.',
    Rashkin2023: 'H. Rashkin, V. Nikolaev, M. Lamm, L. Aroyo, M. Collins, D. Das, S. Petrov, G. S. Tomar, I. Turc, and D. Reitter, "Measuring Attribution in Natural Language Generation Models," Computational Linguistics, vol. 49, no. 4, pp. 777–840, 2023.',
    Gao2023RARR: 'L. Gao, Z. Dai, P. Pasupat et al., "RARR: Researching and Revising What Language Models Say, Using Language Models," in Proc. ACL, 2023, pp. 16477–16508.',
    Huang2023: 'L. Huang, W. Yu, W. Ma et al., "A Survey on Hallucination in Large Language Models: Principles, Taxonomy, Challenges, and Open Questions," ACM Trans. Inf. Syst., 2023. arXiv:2311.05232.',
    Tonmoy2024: 'S. M. T. I. Tonmoy, S. M. M. Zaman, V. Jain, A. Rani, V. Rawte, A. Chadha, and A. Das, "A Comprehensive Survey of Hallucination Mitigation Techniques in Large Language Models," arXiv:2401.01313, 2024.',
    Kamath2020: 'A. Kamath, R. Jia, and P. Liang, "Selective Question Answering under Domain Shift," in Proc. ACL, 2020, pp. 5684–5696.',
    Varshney2022: 'N. Varshney, S. Mishra, and C. Baral, "Investigating Selective Prediction Approaches Across Several Tasks in IID, OOD, and Adversarial Settings," in Findings of ACL, 2022, pp. 1995–2002.',
    Singhal2023: 'K. Singhal, S. Azizi, T. Tu et al., "Large Language Models Encode Clinical Knowledge," Nature, vol. 620, no. 7972, pp. 172–180, 2023.',
    Singhal2025: 'K. Singhal, T. Tu, J. Gottweis et al., "Toward Expert-Level Medical Question Answering with Large Language Models," Nature Medicine, vol. 31, pp. 943–950, 2025.',
    Lee2023NEJM: 'P. Lee, S. Bubeck, and J. Petro, "Benefits, Limits, and Risks of GPT-4 as an AI Chatbot for Medicine," New England J. Medicine, vol. 388, no. 13, pp. 1233–1239, 2023.',
    Thirunavukarasu2023: 'A. J. Thirunavukarasu, D. S. J. Ting, K. Elangovan, L. Gutierrez, T. F. Tan, and D. S. W. Ting, "Large Language Models in Medicine," Nature Medicine, vol. 29, no. 8, pp. 1930–1940, 2023.',
    Goh2024JAMA: 'E. Goh, R. Gallo, J. Hom et al., "Large Language Model Influence on Diagnostic Reasoning: A Randomized Clinical Trial," JAMA Network Open, vol. 7, no. 10, e2440969, 2024.',
    Kanjee2023JAMA: 'Z. Kanjee, B. Crowe, and A. Rodman, "Accuracy of a Generative Artificial Intelligence Model in a Complex Diagnostic Challenge," JAMA, vol. 330, no. 1, pp. 78–80, 2023.',
    Nori2023: 'H. Nori, N. King, S. M. McKinney, D. Carignan, and E. Horvitz, "Capabilities of GPT-4 on Medical Challenge Problems," arXiv:2303.13375, 2023.',
    Bhayana2024: 'R. Bhayana, "Chatbots and Large Language Models in Radiology: A Practical Primer for Clinical and Research Applications," Radiology, vol. 310, no. 1, e232756, 2024.',
    Adams2023: 'L. C. Adams, D. Truhn, F. Busch, A. Kader, S. M. Niehues, M. R. Makowski, and K. K. Bressem, "Leveraging GPT-4 for Post Hoc Transformation of Free-Text Radiology Reports into Structured Reporting: A Multilingual Feasibility Study," Radiology, vol. 307, no. 4, e230725, 2023.',
    Rao2023: 'A. Rao, J. Kim, M. Kamineni, M. Pang, W. Lie, and M. D. Succi, "Evaluating ChatGPT as an Adjunct for Radiologic Decision-Making," J. Am. Coll. Radiol., 2023. doi:10.1016/j.jacr.2023.05.003.',
    Bhayana2023: 'R. Bhayana, S. Krishna, and R. R. Bleakney, "Performance of ChatGPT on a Radiology Board-Style Examination: Insights into Current Strengths and Limitations," Radiology, vol. 307, no. 5, e230582, 2023.',
    Lyu2023: 'Q. Lyu, J. Tan, M. E. Zapadka et al., "Translating Radiology Reports into Plain Language Using ChatGPT and GPT-4 with Prompt Learning," Visual Computing for Industry, Biomedicine, and Art, vol. 6, art. 9, 2023.',
    Elkassem2023: 'A. A. Elkassem and A. D. Smith, "Potential Use Cases for ChatGPT in Radiology Reporting," American J. Roentgenology, vol. 221, no. 3, pp. 373–376, 2023.',
    Rau2023: 'A. Rau, S. Rau, D. Zoeller et al., "A Context-based Chatbot Surpasses Trained Radiologists and Generic ChatGPT in Following the ACR Appropriateness Guidelines," Radiology, vol. 308, no. 1, e230970, 2023.',
    Sistrom2008: 'C. L. Sistrom, "In Support of the ACR Appropriateness Criteria," J. Am. Coll. Radiol., vol. 5, no. 5, pp. 630–635, 2008.',
    ACRMethod2021: 'D. A. Kurth, B. K. Karmazyn, C. A. Waldrip, M. Chatfield, and M. E. Lockhart, "ACR Appropriateness Criteria® Methodology," J. Am. Coll. Radiol., vol. 18, no. 11S, pp. S240–S250, 2021.',
    Sheng2016: 'A. Y. Sheng, A. Castro, and R. E. Lewiss, "Awareness, Utilization, and Education of the ACR Appropriateness Criteria: A Review and Future Directions," J. Am. Coll. Radiol., vol. 13, no. 2, pp. 131–136, 2016.',
    Sistrom2009: 'C. L. Sistrom, P. A. Dang, J. B. Weilburg, K. J. Dreyer, D. I. Rosenthal, and J. H. Thrall, "Effect of Computerized Order Entry With Integrated Decision Support on the Growth of Outpatient Procedure Volumes: Seven-Year Time Series Analysis," Radiology, vol. 251, no. 1, pp. 147–155, 2009.',
    Rosenthal2006: 'D. I. Rosenthal, J. B. Weilburg, T. Schultz et al., "Radiology Order Entry With Decision Support: Initial Clinical Experience," J. Am. Coll. Radiol., vol. 3, no. 10, pp. 799–806, 2006.',
    Xiong2024: 'G. Xiong, Q. Jin, Z. Lu, and A. Zhang, "Benchmarking Retrieval-Augmented Generation for Medicine," in Findings of ACL, 2024, pp. 6233–6251.',
    Zakka2024: 'C. Zakka, R. Shad, A. Chaurasia et al., "Almanac — Retrieval-Augmented Language Models for Clinical Medicine," NEJM AI, vol. 1, no. 2, AIoa2300068, 2024.',
    Ram2023: 'O. Ram, Y. Levine, I. Dalmedigos, D. Muhlgay, A. Shashua, K. Leyton-Brown, and Y. Shoham, "In-Context Retrieval-Augmented Language Models," Trans. Assoc. Comput. Linguistics, vol. 11, pp. 1316–1331, 2023.',
    Liu2024Lost: 'N. F. Liu, K. Lin, J. Hewitt, A. Paranjape, M. Bevilacqua, F. Petroni, and P. Liang, "Lost in the Middle: How Language Models Use Long Contexts," Trans. Assoc. Comput. Linguistics, vol. 12, pp. 157–173, 2024.',
    Gao2023Survey: 'Y. Gao, Y. Xiong, X. Gao, K. Jia, J. Pan, Y. Bi, Y. Dai, J. Sun, M. Wang, and H. Wang, "Retrieval-Augmented Generation for Large Language Models: A Survey," arXiv:2312.10997, 2023.',
    Asai2024: 'A. Asai, Z. Wu, Y. Wang, A. Sil, and H. Hajishirzi, "Self-RAG: Learning to Retrieve, Generate, and Critique through Self-Reflection," in Proc. ICLR, 2024.',
    Jiang2023FLARE: 'Z. Jiang, F. F. Xu, L. Gao et al., "Active Retrieval Augmented Generation," in Proc. EMNLP, 2023, pp. 7969–7992.',
    Izacard2023Atlas: 'G. Izacard, P. Lewis, M. Lomeli et al., "Atlas: Few-Shot Learning with Retrieval Augmented Language Models," J. Machine Learning Research, vol. 24, no. 251, pp. 1–43, 2023.',
    Jin2021MedQA: 'D. Jin, E. Pan, N. Oufattole, W.-H. Weng, H. Fang, and P. Szolovits, "What Disease Does This Patient Have? A Large-Scale Open Domain Question Answering Dataset from Medical Exams," Applied Sciences, vol. 11, no. 14, 6421, 2021.',

    // Angle-specific additions for variants D/E/F
    Pineau2021: 'J. Pineau, P. Vincent-Lamarre, K. Sinha, V. Larivière, A. Beygelzimer, F. d\'Alché-Buc, E. Fox, and H. Larochelle, "Improving Reproducibility in Machine Learning Research (A Report from the NeurIPS 2019 Reproducibility Program)," J. Machine Learning Research, vol. 22, no. 164, pp. 1–20, 2021.',
    Wilkinson2016FAIR: 'M. D. Wilkinson, M. Dumontier, I. J. Aalbersberg et al., "The FAIR Guiding Principles for Scientific Data Management and Stewardship," Scientific Data, vol. 3, art. 160018, 2016.',
    Plesser2018: 'H. E. Plesser, "Reproducibility vs. Replicability: A Brief History of a Confused Terminology," Frontiers in Neuroinformatics, vol. 11, art. 76, 2018.',
    Mitchell2019Cards: 'M. Mitchell, S. Wu, A. Zaldivar, P. Barnes, L. Vasserman, B. Hutchinson, E. Spitzer, I. D. Raji, and T. Gebru, "Model Cards for Model Reporting," in Proc. ACM Conf. on Fairness, Accountability, and Transparency (FAT*/FAccT), 2019, pp. 220–229.',
    Gebru2021Datasheets: 'T. Gebru, J. Morgenstern, B. Vecchione, J. W. Vaughan, H. Wallach, H. Daumé III, and K. Crawford, "Datasheets for Datasets," Communications of the ACM, vol. 64, no. 12, pp. 86–92, 2021.',
    Bender2018DataStmts: 'E. M. Bender and B. Friedman, "Data Statements for Natural Language Processing: Toward Mitigating System Bias and Enabling Better Science," Trans. Assoc. Comput. Linguistics, vol. 6, pp. 587–604, 2018.',
    Kwon2023vLLM: 'W. Kwon, Z. Li, S. Zhuang, Y. Sheng, L. Zheng, C. H. Yu, J. Gonzalez, H. Zhang, and I. Stoica, "Efficient Memory Management for Large Language Model Serving with PagedAttention," in Proc. 29th ACM Symp. on Operating Systems Principles (SOSP), 2023, pp. 611–626.',
    Crankshaw2017Clipper: 'D. Crankshaw, X. Wang, G. Zhou, M. J. Franklin, J. E. Gonzalez, and I. Stoica, "Clipper: A Low-Latency Online Prediction Serving System," in Proc. 14th USENIX Symp. on Networked Systems Design and Implementation (NSDI), 2017, pp. 613–627.',
    Zheng2023MTBench: 'L. Zheng, W.-L. Chiang, Y. Sheng et al., "Judging LLM-as-a-Judge with MT-Bench and Chatbot Arena," in Adv. Neural Inf. Process. Syst. (NeurIPS) Datasets and Benchmarks Track, 2023.',
    Wang2023SC: 'X. Wang, J. Wei, D. Schuurmans, Q. Le, E. Chi, S. Narang, A. Chowdhery, and D. Zhou, "Self-Consistency Improves Chain of Thought Reasoning in Language Models," in Proc. ICLR, 2023.',
    Gao2023HyDE: 'L. Gao, X. Ma, J. Lin, and J. Callan, "Precise Zero-Shot Dense Retrieval without Relevance Labels," in Proc. ACL, 2023, pp. 1762–1777.',
    Yao2023ReAct: 'S. Yao, J. Zhao, D. Yu, N. Du, I. Shafran, K. Narasimhan, and Y. Cao, "ReAct: Synergizing Reasoning and Acting in Language Models," in Proc. ICLR, 2023.',
  }
};
